/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as PatternsSlugRouteImport } from './routes/patterns.$slug'
import { Route as StudioIndustryIdRouteImport } from './routes/studio.$industryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsSlugRoute = PatternsSlugRouteImport.update({
  id: '/patterns/$slug',
  path: '/patterns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndustryIdRoute = StudioIndustryIdRouteImport.update({
  id: '/studio/$industryId',
  path: '/studio/$industryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/studio/$industryId': typeof StudioIndustryIdRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/studio/$industryId': typeof StudioIndustryIdRoute
  '/patterns': typeof PatternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/studio/$industryId': typeof StudioIndustryIdRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/patterns/$slug'
    | '/studio/$industryId'
    | '/patterns/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/patterns/$slug' | '/studio/$industryId' | '/patterns'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/patterns/$slug'
    | '/studio/$industryId'
    | '/patterns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  PatternsSlugRoute: typeof PatternsSlugRoute
  StudioIndustryIdRoute: typeof StudioIndustryIdRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$slug': {
      id: '/patterns/$slug'
      path: '/patterns/$slug'
      fullPath: '/patterns/$slug'
      preLoaderRoute: typeof PatternsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$industryId': {
      id: '/studio/$industryId'
      path: '/studio/$industryId'
      fullPath: '/studio/$industryId'
      preLoaderRoute: typeof StudioIndustryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  PatternsSlugRoute: PatternsSlugRoute,
  StudioIndustryIdRoute: StudioIndustryIdRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
